# Generated by Django 5.1 on 2024-09-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosendy', '0002_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=255)),
                ('template_content', models.TextField()),
                ('file', models.FileField(upload_to='campaign_files/')),
            ],
        ),
    ]
